### ISSUE TITLE
No ability to direct model output to the user directory

### ISSUE THREAD

**Issue by JonahRileyHuggins** [birtwistlelab/SPARCED#25]
There is no innate script in the model that directs the model output into the user's directory.

**Comment by ChocolateCharlie** [comment]
Do you mean that you'd like to pass as an argument the location of where the output should be saved ?
I have a sample `save_output` function [here](https://github.com/ChocolateCharlie/sparced-personal-utilities/blob/master/sparced_pipeline/run_model/run_model_fast_drug_incub.py) (line 44) if it can help. It saves the output in the current directory, but you could add a bit of code at the beginning to store your current location A, move to the desired location B, and then at the end move back to the location A. Could this be useful ?
